baseURL = "https://mumble.info/"
languageCode = "en-us"
title = "Mumble"
theme = "mumble"
publishDir = "../public"

disableKinds = ["taxonomy","taxonomyTerm"]

[permalinks]
  blog = "/blog/:title/"

[[menu.main]]
    title = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    title = "Downloads"
    weight = 2
    identifier = "downloads"
    url = "/downloads"

[[menu.main]]
    title = "Documentation"
    weight = 3
    identifier = "docs"
    url = "/docs"

[[menu.main]]
    title = "Blog"
    weight = 4
    identifier = "blog"
    url = "/blog"

[[menu.main]]
    title = "Forums"
    weight = 5
    identifier = "forums"
    url = "https://www.forums.mumble.info"

[[menu.main]]
    title = "Contribute"
    weight = 6
    identifier = "contribute"
    url = "/contribute"

[[menu.footer]]
    title = "Security"
    weight = 1
    identifier = "security"
    url = "/security"

[[menu.footer]]
    title = "Privacy"
    weight = 2
    identifier = "privacy"
    url = "/privacy"
