baseURL = "https://mumble.info/"
languageCode = "en-us"
title = "Mumble"
publishDir = "../public"

disableKinds = ["taxonomy","taxonomyTerm"]

googleAnalytics = "UA-10674037-3"

[permalinks]
  blog = "/blog/:title/"

# See the config folder for additional configuration
