pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOROOT: '/usr/local/go1.11' # Go installation path
  GO111MODULE: on
  HUGO_VERSION: 0.69.0
  HUGO_SHA: 319cfd6b9ff789f49731ca12dcdd9a5859246f4808e4b67a444d05e18d8c39b5

jobs:
- job: go_webserver
  steps:
  - script: |
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Prepare Go Environment'

  - script: |
      go version
      go get -v .
    workingDirectory: 'src'
    displayName: 'Get Go Webserver Dependencies'

  - script: |
      go version
      go build -v .
      mkdir ../bin
      mv mumble-www ../bin
    workingDirectory: 'src'
    displayName: 'Build Go Webserver'

  - script: |
      go version
      go test
    workingDirectory: 'src'
    displayName: 'Execute Go Webserver Tests'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'mumble-www'
      targetPath: 'bin'

- job: hugo
  steps:
  - script: |
      set -e
      wget --no-verbose https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb -O hugo.deb
      echo "${HUGO_SHA}  hugo.deb" | sha256sum --strict --check
      sudo dpkg -i hugo.deb
      rm hugo.deb
      hugo version
    displayName: 'Prepare Hugo Environment'

  - script: |
      hugo version
      hugo
    displayName: 'Build Hugo Website'
    workingDirectory: 'hugo'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'public'
      targetPath: 'public'
