pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOROOT: '/usr/local/go1.11' # Go installation path
  GO111MODULE: on
  HUGO_VERSION: 0.69.0
  HUGO_SHA: 6c6cf8ad4d517df6589c27b91454ef13f7f7f4d0e7a864755b3f5d2987bb72a5

jobs:
- job: go_webserver
  steps:
  - script: |
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'Prepare Go Environment'

  - script: |
      go version
      go get -v .
    workingDirectory: 'src'
    displayName: 'Get Go Webserver Dependencies'

  - script: |
      go version
      go build -v .
      mkdir ../bin
      mv mumble-www ../bin
    workingDirectory: 'src'
    displayName: 'Build Go Webserver'

  - script: |
      go version
      go test
    workingDirectory: 'src'
    displayName: 'Execute Go Webserver Tests'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'mumble-www'
      targetPath: 'bin'

- job: hugo
  steps:
  - script: |
      set -e
      mkdir hugobin
      wget -O ${HUGO_VERSION}.tar.gz https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
      echo "${HUGO_SHA}  ${HUGO_VERSION}.tar.gz" | sha256sum -c
      tar xf ${HUGO_VERSION}.tar.gz --directory=hugobin hugo
      rm -r ${HUGO_VERSION}.tar.gz
      hugobin/hugo version
    displayName: 'Prepare Hugo Environment'

  - script: |
      ../hugobin/hugo version
      ../hugobin/hugo
    displayName: 'Build Hugo Website'
    workingDirectory: 'hugo'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'public'
      targetPath: 'public'
