baseURL = "https://mumble.info/"
languageCode = "en-us"
title = "Mumble"
theme = "mumble"

disableKinds = ["taxonomy","taxonomyTerm"]

[permalinks]
  blog = "/blog/:title/"

[[menu.main]]
    title = "Home"
    weight = 1
    identifier = "home"
    url = "/"

[[menu.main]]
    title = "Documentation"
    weight = 2
    identifier = "docs"
    url = "/docs"

[[menu.main]]
    title = "Blog"
    weight = 3
    identifier = "blog"
    url = "/blog"

[[menu.main]]
    title = "Forums"
    weight = 4
    identifier = "forums"
    url = "https://www.forums.mumble.info"

[[menu.main]]
    title = "Reporting Bugs"
    weight = 5
    identifier = "bugs"
    url = "https://github.com/mumble-voip/mumble/issues/new"

[[menu.main]]
    title = "Contribute"
    weight = 6
    identifier = "contribute"
    url = "https://github.com/mumble-voip/mumble"

[[menu.footer]]
    title = "Privacy"
    weight = 1
    identifier = "privacy"
    url = "/privacy"

[[menu.footer]]
    title = "Cookies"
    weight = 2
    identifier = "cookies"
    url = "/cookies"

[[menu.footer]]
    title = "Legal"
    weight = 3
    identifier = "legal"
    url = "/legal"
